"""Generate rules/14-browsers.toml: browser policies for Microsoft Edge, Google Chrome and Brave (issue #1).

The source were three .cmd scripts attached to issue #1 of the repository. Every policy name and value was
checked against the vendors' definitions (Microsoft Learn, Chromium and brave-core policy templates,
25.09.2026); names that do not exist, obsolete policies and policies without effect in a workgroup are
listed in docs/technical/reference/18-browsers.md, section "Corrections", and are not generated.

Run after editing the table below:
    cd WinKickOff
    python tools/make_browser_rules.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = "docs/technical/reference/18-browsers.md"
PATHS = {
    "edge": ("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Edge", "browsers.edge", "microsoft-edge", "Edge"),
    "chrome": ("HKLM:\\SOFTWARE\\Policies\\Google\\Chrome", "browsers.chrome", "google-chrome", "Chrome"),
    "brave": ("HKLM:\\SOFTWARE\\Policies\\BraveSoftware\\Brave", "browsers.brave", "brave", "Brave"),
}
COMMENTED = "В сценарии из issue #1 строка закомментирована: включайте осознанно."

# (browser, id suffix, value name, value or (param name, param title, default, [(value, title), ...]),
#  level, title, summary, effect, risk, versions, tags)
RULES: list[tuple] = [
    # ------------------------------------------------------------------ Microsoft Edge
    ("edge", "diagnostic-data-off", "DiagnosticData", 0, "optional",
     "Edge: не отправлять диагностические данные",
     "Edge не отправляет Microsoft ни обязательные, ни необязательные диагностические данные о работе браузера.",
     "Сведения об использовании браузера и посещённых сайтах не уходят в Microsoft. Заменяет устаревшие политики MetricsReportingEnabled и SendSiteInfoToImproveServices из сценария issue #1.",
     "", "Edge 122 и новее на Windows 10 и 11; старые версии Edge подчиняются общей настройке телеметрии Windows.",
     ["телеметрия", "диагностика", "diagnosticdata"]),
    ("edge", "search-telemetry-off", "Edge3PSerpTelemetryEnabled", 0, "optional",
     "Edge: не собирать запросы к сторонним поисковикам",
     "Edge не собирает сведения о поиске в сторонних поисковых системах (телеметрия 3P SERP).",
     "Запросы к Google и другим поисковикам не попадают в телеметрию Edge.",
     "", "Edge 120 и новее.", ["телеметрия", "поиск", "serp"]),
    ("edge", "sidebar-off", "HubsSidebarEnabled", 0, "optional",
     "Edge: скрыть боковую панель",
     "Боковая панель Edge с приложениями и ярлыками не показывается.",
     "Меньше отвлекающих элементов. До Edge 141 вместе с панелью скрывается и кнопка Copilot; с версии 141 значок Copilot управляется политикой, которая действует только для профилей Entra ID.",
     "", "Edge 99 и новее.", ["боковая панель", "sidebar", "copilot"]),
    ("edge", "shopping-off", "EdgeShoppingAssistantEnabled", 0, "optional",
     "Edge: выключить помощника покупок",
     "Edge не показывает сравнение цен, купоны и кэшбэк на сайтах магазинов.",
     "Нет всплывающих предложений на страницах магазинов, и адреса этих страниц не передаются сервису покупок.",
     "", "Edge 87 и новее.", ["покупки", "shopping", "реклама"]),
    ("edge", "rewards-off", "ShowMicrosoftRewards", 0, "optional",
     "Edge: скрыть Microsoft Rewards",
     "Программа бонусов Microsoft Rewards не показывается в Edge, а её переключатель в параметрах выключен.",
     "Нет предложений зарабатывать баллы за поиск и покупки.",
     "", "Edge 88 и новее.", ["rewards", "реклама", "бонусы"]),
    ("edge", "insider-promo-off", "MicrosoftEdgeInsiderPromotionEnabled", 0, "optional",
     "Edge: без рекламы программы Edge Insider",
     "Edge не предлагает установить тестовые сборки браузера.",
     "Пользователи не ставят нестабильные версии Edge по рекламному предложению.",
     "", "Edge 98 и новее.", ["insider", "реклама"]),
    ("edge", "sync-off", "SyncDisabled", 1, "optional",
     "Edge: запретить синхронизацию",
     "Синхронизация избранного, паролей, истории и настроек Edge с облачной учётной записью выключена.",
     "Данные браузера не уходят в облако и не попадают на личные устройства сотрудников.",
     "Избранное и настройки не переносятся между компьютерами пользователя.", "Edge 77 и новее.",
     ["синхронизация", "sync", "облако"]),
    ("edge", "translate-off", "TranslateEnabled", 0, "optional",
     "Edge: не предлагать перевод страниц",
     "Edge не предлагает перевести страницу на другом языке.",
     "Текст страниц не отправляется в облачный переводчик.",
     "Сотрудники, которые читают иностранные сайты, лишаются встроенного перевода.", "Edge 77 и новее.",
     ["перевод", "translate"]),
    ("edge", "web-capture-off", "WebCaptureEnabled", 0, "optional",
     "Edge: выключить веб-снимок",
     "Функция снимка страницы и её фрагментов (Web Capture) недоступна.",
     "Меньше встроенных функций, которые передают содержимое страниц сервисам Microsoft.",
     "Снимки страниц придётся делать средствами Windows.", "Edge 87 и новее.", ["снимок", "web capture"]),
    ("edge", "autofill-address-off", "AutofillAddressEnabled", 0, "optional",
     "Edge: не сохранять адреса для автозаполнения",
     "Edge не сохраняет адреса и не подставляет их в формы.",
     "Личные данные сотрудников не хранятся в профиле браузера.",
     "", "Edge 77 и новее.", ["автозаполнение", "autofill", "адреса"]),
    ("edge", "search-suggest-off", "SearchSuggestEnabled", 0, "optional",
     "Edge: без поисковых подсказок",
     "Адресная строка Edge не показывает подсказки поисковой системы.",
     "Набираемый текст не отправляется поисковику до нажатия Enter.",
     "", "Edge 77 и новее.", ["подсказки", "поиск", "suggest"]),
    ("edge", "feedback-off", "UserFeedbackAllowed", 0, "optional",
     "Edge: без отправки отзывов",
     "Кнопка отзывов и отправка отзывов в Microsoft отключены.",
     "Снимки экрана и описания проблем не уходят из браузера в Microsoft.",
     "", "Edge 77 и новее.", ["отзывы", "feedback"]),
    ("edge", "signin-off", "BrowserSignin", 0, "optional",
     "Edge: запретить вход в браузер",
     "Вход в Edge с учётной записью Microsoft или рабочей учётной записью запрещён.",
     "Профиль браузера остаётся локальным и не связан с облачной учётной записью.",
     "Недоступны синхронизация и функции, которым нужен вход. " + COMMENTED, "Edge 77 и новее.",
     ["вход", "signin", "учётная запись"]),
    ("edge", "password-manager-off", "PasswordManagerEnabled", 0, "risky",
     "Edge: запретить сохранение паролей",
     "Встроенный менеджер паролей Edge не предлагает сохранять пароли.",
     "Пароли не хранятся в профиле браузера.",
     "Без менеджера паролей пользователи чаще повторяют пароли или записывают их. Включать, только если в организации есть отдельный менеджер паролей. " + COMMENTED,
     "Edge 77 и новее.", ["пароли", "password"]),
    ("edge", "autofill-cards-off", "AutofillCreditCardEnabled", 0, "optional",
     "Edge: не сохранять банковские карты",
     "Edge не сохраняет данные банковских карт и не подставляет их в формы.",
     "Данные карт не хранятся в профиле браузера.",
     COMMENTED, "Edge 77 и новее.", ["карты", "autofill", "платежи"]),
    # ------------------------------------------------------------------ Google Chrome
    ("chrome", "metrics-off", "MetricsReportingEnabled", 0, "optional",
     "Chrome: не отправлять статистику и отчёты о сбоях",
     "Chrome не отправляет Google статистику использования и отчёты о сбоях.",
     "Сведения о работе браузера не уходят в Google.",
     "", "Chrome 8 и новее.", ["телеметрия", "статистика", "metrics"]),
    ("chrome", "variations", "ChromeVariations",
     ("mode", "Режим полевых испытаний", 1, [(1, "Только критические исправления безопасности и стабильности"), (2, "Выключить все (не рекомендуется Google)")]),
     "optional",
     "Chrome: ограничить полевые испытания (variations)",
     "Chrome не включает у пользователя экспериментальные функции, которые Google раздаёт без обновления браузера.",
     "Поведение браузера меняется только с обновлениями. Значение 1 сохраняет срочные исправления безопасности.",
     "Значение 2 может задержать критические исправления безопасности: Google его не рекомендует. В сценарии issue #1 было несуществующее имя ChromeVariationsEnabled.",
     "Chrome 83 и новее.", ["variations", "эксперименты", "телеметрия"]),
    ("chrome", "sync", "SyncDisabled",
     ("value", "Синхронизация", 1, [(1, "Запрещена"), (0, "Решает пользователь (как в сценарии issue #1)")]),
     "optional",
     "Chrome: синхронизация с Google",
     "Синхронизация закладок, паролей, истории и настроек Chrome с аккаунтом Google запрещена (или оставлена на выбор пользователя).",
     "Данные браузера не уходят в облако Google и не попадают на личные устройства сотрудников.",
     "В сценарии issue #1 стояло 0, что оставляет выбор пользователю; по умолчанию здесь запрет, как для Edge.",
     "Chrome 8 и новее.", ["синхронизация", "sync", "google"]),
    ("chrome", "background-off", "BackgroundModeEnabled", 0, "optional",
     "Chrome: не работать в фоне после закрытия",
     "Chrome и его приложения не продолжают работать после закрытия последнего окна.",
     "Браузер не занимает память и сеть, когда им не пользуются.",
     "", "Chrome 19 и новее.", ["фон", "background", "память"]),
    ("chrome", "genai-off", "GenAiDefaultSettings", 2, "optional",
     "Chrome: выключить функции генеративного ИИ",
     "Функции генеративного ИИ Chrome (помощь в написании текста, упорядочивание вкладок, поиск по истории и другие) по умолчанию запрещены.",
     "Содержимое страниц и тексты сотрудников не отправляются в модели Google.",
     "", "Chrome 130 и новее.", ["ии", "ai", "gemini", "genai"]),
    ("chrome", "genai-local-model-off", "GenAILocalFoundationalModelSettings", 1, "optional",
     "Chrome: не загружать локальную модель ИИ",
     "Chrome не скачивает на компьютер локальную модель генеративного ИИ.",
     "На диске не появляется модель объёмом в гигабайты, не расходуется трафик.",
     "", "Chrome 124 и новее.", ["ии", "модель", "диск"]),
    ("chrome", "devtools-genai-off", "DevToolsGenAiSettings", 2, "optional",
     "Chrome: выключить ИИ в инструментах разработчика",
     "Функции генеративного ИИ в инструментах разработчика Chrome запрещены.",
     "Код и данные страниц не отправляются в модели Google из DevTools.",
     "", "Chrome 125 и новее.", ["ии", "devtools"]),
    ("chrome", "lens-overlay-off", "LensOverlaySettings", 1, "optional",
     "Chrome: выключить Google Lens поверх страницы",
     "Поиск Google Lens по содержимому экрана (Lens Overlay) недоступен.",
     "Снимки страниц не отправляются в Google для визуального поиска.",
     "В сценарии issue #1 стояло 0, что разрешает функцию; здесь 1. С Chrome 147 политика объявлена устаревшей.",
     "Chrome 126 и новее.", ["lens", "поиск", "ии"]),
    ("chrome", "translate-off", "TranslateEnabled", 0, "optional",
     "Chrome: не предлагать перевод страниц",
     "Chrome не предлагает перевести страницу на другом языке.",
     "Текст страниц не отправляется в облачный переводчик Google.",
     "Сотрудники, которые читают иностранные сайты, лишаются встроенного перевода.", "Chrome 12 и новее.",
     ["перевод", "translate"]),
    ("chrome", "signin-off", "BrowserSignin", 0, "optional",
     "Chrome: запретить вход в браузер",
     "Вход в Chrome с аккаунтом Google запрещён.",
     "Профиль браузера остаётся локальным и не связан с аккаунтом Google.",
     "Недоступны синхронизация и функции, которым нужен вход.", "Chrome 70 и новее.",
     ["вход", "signin", "google"]),
    ("chrome", "search-suggest-off", "SearchSuggestEnabled", 0, "optional",
     "Chrome: без поисковых подсказок",
     "Адресная строка Chrome не показывает подсказки поисковой системы.",
     "Набираемый текст не отправляется поисковику до нажатия Enter.",
     "", "Chrome 8 и новее.", ["подсказки", "поиск", "suggest"]),
    ("chrome", "cast-private-only", "MediaRouterCastAllowAllIPs", 0, "optional",
     "Chrome: трансляция Cast только в локальной сети",
     "Google Cast подключается только к устройствам с частными адресами локальной сети.",
     "Экран нельзя транслировать на устройства с публичными адресами.",
     "", "Chrome 67 и новее.", ["cast", "трансляция", "сеть"]),
    ("chrome", "promotions-off", "PromotionsEnabled", 0, "optional",
     "Chrome: без рекламных страниц и акций",
     "Chrome не показывает рекламные вкладки и акции Google.",
     "Меньше рекламы при запуске и обновлении браузера. Заменяет устаревшую политику PromotionalTabsEnabled из сценария issue #1.",
     "", "Chrome 128 и новее.", ["реклама", "promotions"]),
    ("chrome", "password-manager-off", "PasswordManagerEnabled", 0, "risky",
     "Chrome: запретить сохранение паролей",
     "Встроенный менеджер паролей Chrome не предлагает сохранять пароли.",
     "Пароли не хранятся в профиле браузера.",
     "Без менеджера паролей пользователи чаще повторяют пароли или записывают их. Включать, только если в организации есть отдельный менеджер паролей. " + COMMENTED,
     "Chrome 8 и новее.", ["пароли", "password"]),
    ("chrome", "autofill-address-off", "AutofillAddressEnabled", 0, "optional",
     "Chrome: не сохранять адреса для автозаполнения",
     "Chrome не сохраняет адреса и не подставляет их в формы.",
     "Личные данные сотрудников не хранятся в профиле браузера.",
     COMMENTED, "Chrome 69 и новее.", ["автозаполнение", "autofill", "адреса"]),
    ("chrome", "autofill-cards-off", "AutofillCreditCardEnabled", 0, "optional",
     "Chrome: не сохранять банковские карты",
     "Chrome не сохраняет данные банковских карт и не подставляет их в формы.",
     "Данные карт не хранятся в профиле браузера.",
     COMMENTED, "Chrome 63 и новее.", ["карты", "autofill", "платежи"]),
    ("chrome", "builtin-dns-off", "BuiltInDnsClientEnabled", 0, "optional",
     "Chrome: DNS Windows вместо встроенного клиента",
     "Chrome разрешает имена через DNS-клиент Windows, а не через свой встроенный.",
     "Действуют DNS-настройки организации, файл hosts и фильтрующий DNS, если он есть.",
     COMMENTED, "Chrome 25 и новее.", ["dns", "сеть"]),
    # ------------------------------------------------------------------ Brave
    ("brave", "rewards-off", "BraveRewardsDisabled", 1, "optional",
     "Brave: выключить Brave Rewards",
     "Программа вознаграждений за просмотр рекламы Brave Rewards недоступна.",
     "Браузер не показывает собственную рекламу и не начисляет токены.",
     "", "Политики Brave; действуют, если Brave установлен.", ["rewards", "реклама", "криптовалюта"]),
    ("brave", "wallet-off", "BraveWalletDisabled", 1, "optional",
     "Brave: выключить криптокошелёк",
     "Встроенный криптовалютный кошелёк Brave Wallet недоступен.",
     "На рабочих компьютерах не появляются кошельки и расширения для криптовалют.",
     "", "Политики Brave; действуют, если Brave установлен.", ["wallet", "криптовалюта"]),
    ("brave", "vpn-off", "BraveVPNDisabled", 1, "optional",
     "Brave: выключить Brave VPN",
     "Платный VPN Brave недоступен.",
     "Трафик браузера не уходит в VPN в обход сетевых правил организации.",
     "", "Политики Brave; действуют, если Brave установлен.", ["vpn", "сеть"]),
    ("brave", "ai-chat-off", "BraveAIChatEnabled", 0, "optional",
     "Brave: выключить ИИ-помощника Leo",
     "ИИ-помощник Leo (AI Chat) в Brave недоступен.",
     "Содержимое страниц и тексты сотрудников не отправляются в модели ИИ. В сценарии issue #1 было также несуществующее имя BraveLeoEnabled.",
     "", "Политики Brave; действуют, если Brave установлен.", ["ии", "leo", "ai"]),
    ("brave", "stats-ping-off", "BraveStatsPingEnabled", 0, "optional",
     "Brave: без ежедневного отчёта об использовании",
     "Brave не отправляет ежедневный анонимный сигнал об использовании (stats ping).",
     "Меньше обращений браузера к серверам Brave. В сценарии issue #1 было также несуществующее имя BraveStatsPingDisabled.",
     "", "Политики Brave; действуют, если Brave установлен.", ["телеметрия", "stats"]),
    ("brave", "p3a-off", "BraveP3AEnabled", 0, "optional",
     "Brave: без аналитики продукта (P3A)",
     "Brave не отправляет обезличенную аналитику продукта P3A.",
     "Сведения об использовании функций браузера не уходят в Brave. В сценарии issue #1 было несуществующее имя BraveP3ADisabled.",
     "", "Политики Brave; действуют, если Brave установлен.", ["телеметрия", "p3a"]),
    ("brave", "news-off", "BraveNewsDisabled", 1, "optional",
     "Brave: выключить Brave News",
     "Лента новостей Brave News на новой вкладке недоступна.",
     "Новая вкладка без новостей и рекламных материалов.",
     "", "Политики Brave; действуют, если Brave установлен.", ["новости", "news"]),
    ("brave", "talk-off", "BraveTalkDisabled", 1, "optional",
     "Brave: выключить Brave Talk",
     "Сервис видеозвонков Brave Talk недоступен.",
     "Видеосвязь идёт только через утверждённые в организации сервисы.",
     "", "Политики Brave; действуют, если Brave установлен.", ["talk", "видеозвонки"]),
    ("brave", "playlist-off", "BravePlaylistEnabled", 0, "optional",
     "Brave: выключить Playlist",
     "Функция сохранения видео и аудио для офлайн-просмотра (Playlist) недоступна.",
     "Медиафайлы не накапливаются в профиле браузера.",
     "", "Политики Brave; действуют, если Brave установлен.", ["playlist", "медиа"]),
    ("brave", "speedreader-off", "BraveSpeedreaderEnabled", 0, "optional",
     "Brave: выключить Speedreader",
     "Режим упрощённого чтения Speedreader недоступен.",
     "Меньше встроенных функций, меняющих вид страниц.",
     "", "Политики Brave; действуют, если Brave установлен.", ["speedreader", "чтение"]),
    ("brave", "wayback-off", "BraveWaybackMachineEnabled", 0, "optional",
     "Brave: без подсказок Wayback Machine",
     "Brave не предлагает открыть архивную копию недоступной страницы в Wayback Machine.",
     "Адреса недоступных страниц не отправляются в архив интернета.",
     "", "Политики Brave; действуют, если Brave установлен.", ["wayback", "архив"]),
    ("brave", "web-discovery-off", "BraveWebDiscoveryEnabled", 0, "optional",
     "Brave: выключить Web Discovery",
     "Brave не передаёт сведения о посещённых страницах для наполнения своего поискового индекса.",
     "Адреса посещённых сайтов не уходят в Brave Search.",
     "", "Политики Brave; действуют, если Brave установлен.", ["web discovery", "поиск", "телеметрия"]),
    ("brave", "translate-off", "TranslateEnabled", 0, "optional",
     "Brave: не предлагать перевод страниц",
     "Brave не предлагает перевести страницу на другом языке.",
     "Текст страниц не отправляется в облачный переводчик.",
     "Сотрудники, которые читают иностранные сайты, лишаются встроенного перевода.",
     "Политики Brave; действуют, если Brave установлен.", ["перевод", "translate"]),
    ("brave", "tor-off", "TorDisabled", 1, "recommended",
     "Brave: запретить окна Tor",
     "Приватные окна с подключением к сети Tor в Brave недоступны.",
     "Трафик браузера не уходит в сеть Tor в обход фильтрации и журналов организации.",
     "", "Политики Brave; действуют, если Brave установлен.", ["tor", "сеть", "анонимность"]),
]


# Rules on by default, so in the «Офис» (Office) preset: the selection made on 26.09.2026 in commit d33fc41.
# The rest (sync, sign-in, sidebar, password managers and others that change what users see) stay off.
DEFAULT_ON = {
    "edge.diagnostic-data-off", "edge.search-telemetry-off", "edge.shopping-off", "edge.rewards-off",
    "edge.insider-promo-off", "edge.translate-off", "edge.feedback-off", "edge.autofill-cards-off",
    "chrome.metrics-off", "chrome.variations", "chrome.background-off", "chrome.genai-off",
    "chrome.genai-local-model-off", "chrome.devtools-genai-off", "chrome.translate-off", "chrome.cast-private-only",
    "chrome.promotions-off", "chrome.autofill-cards-off",
    "brave.rewards-off", "brave.wallet-off", "brave.vpn-off", "brave.ai-chat-off", "brave.stats-ping-off",
    "brave.p3a-off", "brave.news-off", "brave.talk-off", "brave.playlist-off", "brave.speedreader-off",
    "brave.wayback-off", "brave.web-discovery-off", "brave.translate-off", "brave.tor-off",
}


def q(text: str) -> str:
    assert '"' not in text and "\\" not in text, text
    return f'"{text}"'


def render() -> str:
    known = {f"{r[0]}.{r[1]}" for r in RULES}
    assert DEFAULT_ON <= known, sorted(DEFAULT_ON - known)
    out = [
        "# Браузеры: Microsoft Edge, Google Chrome, Brave (issue #1). Создаётся tools/make_browser_rules.py;",
        "# правьте таблицу в этом инструменте, а не файл. Включённые по умолчанию правила перечислены в DEFAULT_ON.",
        "",
    ]
    for browser, suffix, name, value, level, title, summary, effect, risk, versions, tags in RULES:
        path, group, anchor, product = PATHS[browser]
        out += [
            "[[rule]]",
            f'id = "{browser}.{suffix}"',
            f'group = "{group}"',
            'phase = "specialize"',
            f"title = {q(title)}",
            f'level = "{level}"',
            f"default = {'true' if f'{browser}.{suffix}' in DEFAULT_ON else 'false'}",
            "tags = [" + ", ".join(q(t) for t in dict.fromkeys([product.lower(), "браузер", "политика", name.lower()] + tags)) + "]",
            f'doc = "{DOC}#{anchor}"',
            f"summary = {q(summary)}",
            f"effect = {q(effect)}",
        ]
        if risk:
            out.append(f"risk = {q(risk)}")
        out.append(f"versions = {q(versions)}")
        param = value if isinstance(value, tuple) else None
        if param:
            pname, ptitle, default, options = param
            out += ["", f"[rule.params.{pname}]", 'type = "enum"', f"title = {q(ptitle)}", f"default = {default}",
                    "values = [ " + ", ".join(f"{{ value = {v}, title = {q(t)} }}" for v, t in options) + " ]"]
        out += ["", "[[rule.actions]]", 'type = "reg"', f"path = '{path}'", f'name = "{name}"', 'kind = "DWord"',
                f'value = "{{{param[0]}}}"' if param else f"value = {value}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    target = ROOT / "rules" / "14-browsers.toml"
    target.write_bytes(render().replace("\n", "\r\n").encode("utf-8"))
    print(f"written {target.relative_to(ROOT)}: {len(RULES)} rules")
