"""Generate rules/14-browsers.json: browser policies for Microsoft Edge, Google Chrome and Brave (issue #1).

The source were three .cmd scripts attached to issue #1 of the repository. Every policy name and value was
checked against the vendors' definitions (Microsoft Learn, Chromium and brave-core policy templates,
25.09.2026); names that do not exist, obsolete policies and policies without effect in a workgroup are
listed in docs/technical/reference/18-browsers.md, section "Corrections", and are not generated.

Run after editing the table below:
    cd WinKickOff
    python tools/make_browser_rules.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from winkickoff.core import jsonfile  # noqa: E402

DOC = "docs/technical/reference/18-browsers.md"
PATHS = {
    "edge": ("HKLM:\\SOFTWARE\\Policies\\Microsoft\\Edge", "browsers.edge", "microsoft-edge", "Edge"),
    "chrome": ("HKLM:\\SOFTWARE\\Policies\\Google\\Chrome", "browsers.chrome", "google-chrome", "Chrome"),
    "brave": ("HKLM:\\SOFTWARE\\Policies\\BraveSoftware\\Brave", "browsers.brave", "brave", "Brave"),
}
# (browser, id suffix, value name, value or (param name, param title, default, [(value, title), ...]),
#  level, title, summary, effect, risk, versions, extra tags); the texts are English, translations live in
#  rules/lang/<code>.json
RULES: list[tuple] = [
    # ------------------------------------------------------------------ Microsoft Edge
    ("edge", "diagnostic-data-off", "DiagnosticData", 0, "optional",
     "Edge: do not send diagnostic data",
     "Edge does not send required or optional diagnostic data about the browser to Microsoft.",
     "Information about browser usage and visited sites is not sent to Microsoft. Replaces the deprecated MetricsReportingEnabled and SendSiteInfoToImproveServices policies from the issue #1 script.",
     "", "Edge 122 and later on Windows 10 and 11; older versions of Edge follow the general Windows telemetry setting.",
     ["telemetry", "diagnostics"]),
    ("edge", "search-telemetry-off", "Edge3PSerpTelemetryEnabled", 0, "optional",
     "Edge: do not collect queries to third-party search engines",
     "Edge does not collect information about searches on third-party search engines (3P SERP telemetry).",
     "Queries to Google and other search engines are not included in Edge telemetry.",
     "", "Edge 120 and later.",
     ["telemetry", "search", "serp"]),
    ("edge", "sidebar-off", "HubsSidebarEnabled", 0, "optional",
     "Edge: hide the sidebar",
     "The Edge sidebar with apps and shortcuts is not shown.",
     "Fewer distracting elements. Before Edge 141, hiding the sidebar also hides the Copilot button; starting with version 141, the Copilot icon is controlled by a policy that applies only to Entra ID profiles.",
     "", "Edge 99 and later.",
     ["sidebar", "copilot"]),
    ("edge", "shopping-off", "EdgeShoppingAssistantEnabled", 0, "optional",
     "Edge: turn off the shopping assistant",
     "Edge does not show price comparisons, coupons or cashback on store websites.",
     "No pop-up offers on store pages, and the addresses of those pages are not sent to the shopping service.",
     "", "Edge 87 and later.",
     ["shopping", "ads"]),
    ("edge", "rewards-off", "ShowMicrosoftRewards", 0, "optional",
     "Edge: hide Microsoft Rewards",
     "The Microsoft Rewards bonus program is not shown in Edge, and its switch in settings is turned off.",
     "No offers to earn points for searches and purchases.",
     "", "Edge 88 and later.",
     ["rewards", "ads"]),
    ("edge", "insider-promo-off", "MicrosoftEdgeInsiderPromotionEnabled", 0, "optional",
     "Edge: no Edge Insider program promotion",
     "Edge does not offer to install preview builds of the browser.",
     "Users do not install unstable versions of Edge in response to a promotional offer.",
     "", "Edge 98 and later.",
     ["insider", "ads"]),
    ("edge", "sync-off", "SyncDisabled", 1, "optional",
     "Edge: block sync",
     "Sync of Edge favorites, passwords, history and settings with a cloud account is turned off.",
     "Browser data does not go to the cloud and does not end up on employees' personal devices.",
     "Favorites and settings are not carried over between the user's computers.", "Edge 77 and later.",
     ["sync", "cloud"]),
    ("edge", "translate-off", "TranslateEnabled", 0, "optional",
     "Edge: do not offer page translation",
     "Edge does not offer to translate a page written in another language.",
     "Page text is not sent to a cloud translation service.",
     "Employees who read foreign-language websites lose built-in translation.", "Edge 77 and later.",
     ["translation", "translate"]),
    ("edge", "web-capture-off", "WebCaptureEnabled", 0, "optional",
     "Edge: turn off Web Capture",
     "The feature for capturing a page or parts of it (Web Capture) is unavailable.",
     "Fewer built-in features that send page content to Microsoft services.",
     "Page screenshots have to be taken with Windows tools.", "Edge 87 and later.",
     ["capture", "web capture"]),
    ("edge", "autofill-address-off", "AutofillAddressEnabled", 0, "optional",
     "Edge: do not save addresses for autofill",
     "Edge does not save addresses or fill them into forms.",
     "Employees' personal data is not stored in the browser profile.",
     "", "Edge 77 and later.",
     ["autofill", "addresses"]),
    ("edge", "search-suggest-off", "SearchSuggestEnabled", 0, "optional",
     "Edge: no search suggestions",
     "The Edge address bar does not show search engine suggestions.",
     "Typed text is not sent to the search engine until Enter is pressed.",
     "", "Edge 77 and later.",
     ["suggestions", "search", "suggest"]),
    ("edge", "feedback-off", "UserFeedbackAllowed", 0, "optional",
     "Edge: no feedback submission",
     "The feedback button and sending feedback to Microsoft are disabled.",
     "Screenshots and problem descriptions are not sent from the browser to Microsoft.",
     "", "Edge 77 and later.",
     ["feedback"]),
    ("edge", "signin-off", "BrowserSignin", 0, "optional",
     "Edge: block browser sign-in",
     "Signing in to Edge with a Microsoft account or a work account is blocked.",
     "The browser profile stays local and is not linked to a cloud account. Most Edge AI policies do not apply to a profile signed in with a personal Microsoft account: blocking sign-in is needed for them to work.",
     "Sync and features that require sign-in are unavailable.", "Edge 77 and later.",
     ["sign-in", "signin", "account"]),
    ("edge", "password-manager-off", "PasswordManagerEnabled", 0, "risky",
     "Edge: block password saving",
     "The built-in Edge password manager does not offer to save passwords.",
     "Passwords are not stored in the browser profile.",
     "Without a password manager, users reuse passwords or write them down more often. Enable only if the organization has a separate password manager. In the issue #1 script this line is commented out: enable it deliberately.", "Edge 77 and later.",
     ["passwords", "password"]),
    ("edge", "autofill-cards-off", "AutofillCreditCardEnabled", 0, "optional",
     "Edge: do not save payment cards",
     "Edge does not save payment card details or fill them into forms.",
     "Card details are not stored in the browser profile.",
     "In the issue #1 script this line is commented out: enable it deliberately.", "Edge 77 and later.",
     ["maps", "autofill", "payments"]),
    ("edge", "genai-local-model-off", "GenAILocalFoundationalModelSettings", 1, "optional",
     "Edge: do not download the local AI model",
     "Edge does not download the local generative AI model and deletes one that has already been downloaded.",
     "Gigabytes of disk space and traffic are not spent; browser features and websites do not work with the local model.",
     "", "Edge 132 and later. Also applies to a profile signed in with a personal Microsoft account.",
     ["ai", "genai", "model"]),
    ("edge", "builtin-ai-apis-off", "BuiltInAIAPIsEnabled", 0, "optional",
     "Edge: block built-in AI features for websites",
     "Websites cannot call the AI programming interfaces built into the browser (LanguageModel, Summarizer, Writer, Rewriter).",
     "Pages do not process the user's text with the browser's model.",
     "", "Edge 138 and later.",
     ["ai", "api"]),
    ("edge", "history-ai-search-off", "EdgeHistoryAISearchEnabled", 0, "optional",
     "Edge: history search without AI",
     "Browsing history search works by exact match only, without synonyms or natural language queries.",
     "Browsing history is not processed by AI features.",
     "", "Edge 138 and later.",
     ["ai", "logging", "history"]),
    ("edge", "ai-themes-off", "AIGenThemesEnabled", 0, "optional",
     "Edge: no AI-generated themes",
     "Creating browser themes with generative AI (DALL-E) is unavailable.",
     "Theme descriptions are not sent to a cloud image generator.",
     "", "Edge 122 and later.",
     ["ai", "themes", "dall-e"]),
    ("edge", "text-prediction-off", "TextPredictionEnabled", 0, "optional",
     "Edge: no cloud suggestions while typing",
     "Edge does not suggest phrase completions in text fields (Microsoft cloud predictions).",
     "Text typed on websites is not sent to the cloud prediction service.",
     "", "Edge 104 and later.",
     ["ai", "suggestions", "typing"]),
    ("edge", "tab-services-off", "TabServicesEnabled", 0, "optional",
     "Edge: no cloud tab grouping",
     "Tab addresses and titles are not sent to a Microsoft service for automatic grouping and group names.",
     "The list of open tabs stays in the browser.",
     "", "Edge 113 and later.",
     ["ai", "tabs"]),
    ("edge", "autofill-ml-off", "EdgeAutofillMlEnabled", 0, "optional",
     "Edge: autofill without cloud machine learning",
     "Edge does not use cloud machine learning for suggestions when filling in forms.",
     "Form contents are not analyzed by a cloud model.",
     "", "Edge 132 and later.",
     ["ai", "autofill"]),
    ("edge", "copilot-address-bar-off", "CopilotAddressBarSuggestionsEnabled", 0, "optional",
     "Edge: no Copilot suggestions in the address bar",
     "The address bar does not offer to continue a query in Copilot chat.",
     "Queries from the address bar do not go to Copilot.",
     "", "Edge 149 and later.",
     ["copilot", "ai", "address bar"]),
    ("edge", "ntp-copilot-off", "NewTabPageBingChatEnabled", 0, "optional",
     "Edge: remove Copilot from the new tab page",
     "Entry points to Copilot chat (Bing Chat) are removed from the new tab page.",
     "Fewer offers to switch to Copilot. The vendor does not explicitly describe the effect on the new tab page of a profile that is not signed in to an account.",
     "", "Edge 117 and later.",
     ["copilot", "new tab", "bing"]),
    ("edge", "copilot-cowork-off", "CopilotCoworkToolActionsEnabled", 0, "optional",
     "Edge: Copilot does not act for the user",
     "The Cowork feature does not perform actions in the browser on behalf of the user, and the user cannot change this.",
     "The AI agent does not click buttons or fill in forms on websites.",
     "", "Edge 152 and later.",
     ["copilot", "agent", "cowork"]),
    ("edge", "browsing-with-copilot-off", "AllowBrowsingWithCopilot", 0, "optional",
     "Edge: block browsing websites together with Copilot",
     "The mode in which Copilot opens and browses pages on its own (agentic browsing) is turned off and locked.",
     "The AI agent does not visit websites on behalf of the user.",
     "", "Edge 148 and later; the feature itself requires a Microsoft 365 Copilot subscription.",
     ["copilot", "agent"]),
    ("edge", "copilot-page-context-off", "CopilotPageContext", 0, "optional",
     "Edge: Copilot does not read pages (Entra ID profiles)",
     "Copilot in the sidebar does not get the content of open pages.",
     "Applies only to Microsoft Entra ID profiles; in a workgroup with local accounts and browser sign-in blocked it has no effect. On according to the customer's list in case someone signs in through Entra ID.",
     "", "Edge 124 and later; Microsoft Entra ID profiles only.",
     ["copilot", "entra", "page content"]),
    ("edge", "entra-copilot-page-context-off", "EdgeEntraCopilotPageContext", 0, "optional",
     "Edge: Copilot with data protection does not read pages and history (Entra ID profiles)",
     "Microsoft 365 Copilot Chat in the sidebar does not get page content, history or video transcripts.",
     "Applies only to Microsoft Entra ID profiles; in a workgroup with local accounts and browser sign-in blocked it has no effect. On according to the customer's list in case someone signs in through Entra ID.",
     "", "Edge 130 and later; Microsoft Entra ID profiles only.",
     ["copilot", "entra", "logging"]),
    ("edge", "m365-copilot-icon-off", "Microsoft365CopilotChatIconEnabled", 0, "optional",
     "Edge: hide the Microsoft 365 Copilot Chat icon (Entra ID profiles)",
     "The Microsoft 365 Copilot Chat icon is not shown on the toolbar of Edge for Business.",
     "Applies only to Microsoft Entra ID profiles; in a workgroup with local accounts and browser sign-in blocked it has no effect. On according to the customer's list in case someone signs in through Entra ID.",
     "", "Edge 139 and later; Microsoft Entra ID profiles only.",
     ["copilot", "entra", "icon"]),
    ("edge", "compose-inline-off", "ComposeInlineEnabled", 0, "optional",
     "Edge: no Copilot text rewriting (Entra ID profiles)",
     "Rewriting selected text through the context menu (the Microsoft 365 Copilot writing assistant) is unavailable.",
     "Applies only to Microsoft Entra ID profiles; in a workgroup with local accounts and browser sign-in blocked it has no effect. On according to the customer's list in case someone signs in through Entra ID.",
     "", "Edge 115 and later; Microsoft Entra ID accounts only.",
     ["copilot", "entra", "rewrite"]),
    ("edge", "copilot-search-history-off", "ShareBrowsingHistoryWithCopilotSearchAllowed", 0, "optional",
     "Edge: do not share history with Microsoft 365 Copilot Search (Entra ID profiles)",
     "Edge browsing history is not shared with Microsoft 365 Copilot search.",
     "Applies only to Microsoft Entra ID profiles; in a workgroup with local accounts and browser sign-in blocked it has no effect. On according to the customer's list in case someone signs in through Entra ID.",
     "", "Edge 143 and later; sign-in through Microsoft Entra ID and a Microsoft 365 Copilot license.",
     ["copilot", "entra", "logging"]),
    ("edge", "visual-search-off", "VisualSearchEnabled", 0, "optional",
     "Edge: no Bing visual search",
     "Image search through Bing from the image menu, the context menu and the sidebar is unavailable.",
     "Images from pages are not sent to Bing to find similar ones.",
     "The user cannot look for similar images from the browser.", "Edge 95 and later.",
     ["search", "images", "bing"]),
    ("edge", "search-in-sidebar-off", "SearchInSidebarEnabled", 2, "optional",
     "Edge: search results not in the sidebar",
     "Search results for selected text do not open in the sidebar.",
     "Fewer sidebar elements; search opens in a regular tab.",
     "", "Edge 110 and later.",
     ["search", "sidebar"]),
    # ------------------------------------------------------------------ Google Chrome
    ("chrome", "metrics-off", "MetricsReportingEnabled", 0, "optional",
     "Chrome: do not send usage statistics and crash reports",
     "Chrome does not send usage statistics and crash reports to Google.",
     "Information about browser operation is not sent to Google.",
     "", "Chrome 8 and later.",
     ["telemetry", "statistics", "metrics"]),
    ("chrome", "variations", "ChromeVariations", ("mode", "Field trials mode", 1, [(1, "Critical security and stability fixes only"), (2, "Disable all (not recommended by Google)")]), "optional",
     "Chrome: limit field trials (variations)",
     "Chrome does not enable experimental features for the user that Google rolls out without a browser update.",
     "Browser behavior changes only with updates. Value 1 keeps urgent security fixes.",
     "Value 2 may delay critical security fixes: Google does not recommend it. The issue #1 script used the nonexistent name ChromeVariationsEnabled.", "Chrome 83 and later.",
     ["variations", "experiments", "telemetry"]),
    ("chrome", "sync", "SyncDisabled", ("value", "Sync", 1, [(1, "Blocked"), (0, "User decides (as in the issue #1 script)")]), "optional",
     "Chrome: sync with Google",
     "Sync of Chrome bookmarks, passwords, history and settings with a Google account is blocked (or left to the user's choice).",
     "Browser data does not go to the Google cloud and does not end up on employees' personal devices.",
     "The issue #1 script set 0, which leaves the choice to the user; here the default is to block it, as for Edge.", "Chrome 8 and later.",
     ["sync", "google"]),
    ("chrome", "background-off", "BackgroundModeEnabled", 0, "optional",
     "Chrome: do not run in the background after closing",
     "Chrome and its apps do not keep running after the last window is closed.",
     "The browser does not use memory or network when it is not in use.",
     "", "Chrome 19 and later.",
     ["background", "memory"]),
    ("chrome", "genai-off", "GenAiDefaultSettings", 2, "optional",
     "Chrome: turn off generative AI features",
     "Chrome generative AI features (writing help, tab organization, history search and others) are blocked by default.",
     "Page content and employees' texts are not sent to Google models.",
     "", "Chrome 130 and later.",
     ["ai", "gemini", "genai"]),
    ("chrome", "genai-local-model-off", "GenAILocalFoundationalModelSettings", 1, "optional",
     "Chrome: do not download the local AI model",
     "Chrome does not download a local generative AI model to the computer.",
     "A model several gigabytes in size does not appear on the disk, and no network traffic is spent.",
     "", "Chrome 124 and later.",
     ["ai", "model", "disk"]),
    ("chrome", "devtools-genai-off", "DevToolsGenAiSettings", 2, "optional",
     "Chrome: turn off AI in developer tools",
     "Generative AI features in Chrome developer tools are blocked.",
     "Page code and data are not sent to Google models from DevTools.",
     "", "Chrome 125 and later.",
     ["ai", "devtools"]),
    ("chrome", "lens-overlay-off", "LensOverlaySettings", 1, "optional",
     "Chrome: turn off Google Lens over the page",
     "Google Lens search of screen content (Lens Overlay) is unavailable.",
     "Page screenshots are not sent to Google for visual search.",
     "The issue #1 script set 0, which allows the feature; here it is 1. Starting with Chrome 147, the policy is deprecated.", "Chrome 126 and later.",
     ["lens", "search", "ai"]),
    ("chrome", "translate-off", "TranslateEnabled", 0, "optional",
     "Chrome: do not offer page translation",
     "Chrome does not offer to translate a page written in another language.",
     "Page text is not sent to the Google cloud translation service.",
     "Employees who read foreign-language websites lose built-in translation.", "Chrome 12 and later.",
     ["translation", "translate"]),
    ("chrome", "signin-off", "BrowserSignin", 0, "optional",
     "Chrome: block browser sign-in",
     "Signing in to Chrome with a Google account is blocked.",
     "The browser profile stays local and is not linked to a Google account.",
     "Sync and features that require sign-in are unavailable.", "Chrome 70 and later.",
     ["sign-in", "signin", "google"]),
    ("chrome", "search-suggest-off", "SearchSuggestEnabled", 0, "optional",
     "Chrome: no search suggestions",
     "The Chrome address bar does not show search engine suggestions.",
     "Typed text is not sent to the search engine until Enter is pressed.",
     "", "Chrome 8 and later.",
     ["suggestions", "search", "suggest"]),
    ("chrome", "cast-private-only", "MediaRouterCastAllowAllIPs", 0, "optional",
     "Chrome: Cast only on the local network",
     "Google Cast connects only to devices with private local network addresses.",
     "The screen cannot be cast to devices with public addresses.",
     "", "Chrome 67 and later.",
     ["cast", "casting", "network"]),
    ("chrome", "promotions-off", "PromotionsEnabled", 0, "optional",
     "Chrome: no promotional pages or campaigns",
     "Chrome does not show Google promotional tabs and campaigns.",
     "Less advertising when the browser starts and updates. Replaces the deprecated PromotionalTabsEnabled policy from the issue #1 script.",
     "", "Chrome 128 and later.",
     ["ads", "promotions"]),
    ("chrome", "password-manager-off", "PasswordManagerEnabled", 0, "risky",
     "Chrome: block password saving",
     "The built-in Chrome password manager does not offer to save passwords.",
     "Passwords are not stored in the browser profile.",
     "Without a password manager, users reuse passwords or write them down more often. Enable only if the organization has a separate password manager. In the issue #1 script this line is commented out: enable it deliberately.", "Chrome 8 and later.",
     ["passwords", "password"]),
    ("chrome", "autofill-address-off", "AutofillAddressEnabled", 0, "optional",
     "Chrome: do not save addresses for autofill",
     "Chrome does not save addresses or fill them into forms.",
     "Employees' personal data is not stored in the browser profile.",
     "In the issue #1 script this line is commented out: enable it deliberately.", "Chrome 69 and later.",
     ["autofill", "addresses"]),
    ("chrome", "autofill-cards-off", "AutofillCreditCardEnabled", 0, "optional",
     "Chrome: do not save payment cards",
     "Chrome does not save payment card details or fill them into forms.",
     "Card details are not stored in the browser profile.",
     "In the issue #1 script this line is commented out: enable it deliberately.", "Chrome 63 and later.",
     ["maps", "autofill", "payments"]),
    ("chrome", "builtin-dns-off", "BuiltInDnsClientEnabled", 0, "optional",
     "Chrome: Windows DNS instead of the built-in client",
     "Chrome resolves names through the Windows DNS client rather than its own built-in one.",
     "The organization's DNS settings, the hosts file and filtering DNS, if any, take effect.",
     "In the issue #1 script this line is commented out: enable it deliberately.", "Chrome 25 and later.",
     ["dns", "network"]),
    # ------------------------------------------------------------------ Brave
    ("brave", "rewards-off", "BraveRewardsDisabled", 1, "optional",
     "Brave: turn off Brave Rewards",
     "The Brave Rewards program, which rewards users for viewing ads, is unavailable.",
     "The browser does not show its own ads and does not award tokens.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["rewards", "ads", "cryptocurrency"]),
    ("brave", "wallet-off", "BraveWalletDisabled", 1, "optional",
     "Brave: turn off the crypto wallet",
     "The built-in Brave Wallet cryptocurrency wallet is unavailable.",
     "Cryptocurrency wallets and extensions do not appear on work computers.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["wallet", "cryptocurrency"]),
    ("brave", "vpn-off", "BraveVPNDisabled", 1, "optional",
     "Brave: turn off Brave VPN",
     "The paid Brave VPN is unavailable.",
     "Browser traffic does not go through a VPN, bypassing the organization's network rules.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["vpn", "network"]),
    ("brave", "ai-chat-off", "BraveAIChatEnabled", 0, "optional",
     "Brave: turn off the Leo AI assistant",
     "The Leo AI assistant (AI Chat) in Brave is unavailable.",
     "Page content and employees' texts are not sent to AI models. The issue #1 script also used the nonexistent name BraveLeoEnabled.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["ai", "leo"]),
    ("brave", "stats-ping-off", "BraveStatsPingEnabled", 0, "optional",
     "Brave: no daily usage report",
     "Brave does not send the daily anonymous usage signal (stats ping).",
     "Fewer browser connections to Brave servers. The issue #1 script also used the nonexistent name BraveStatsPingDisabled.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["telemetry", "stats"]),
    ("brave", "p3a-off", "BraveP3AEnabled", 0, "optional",
     "Brave: no product analytics (P3A)",
     "Brave does not send anonymized P3A product analytics.",
     "Information about the use of browser features is not sent to Brave. The issue #1 script used the nonexistent name BraveP3ADisabled.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["telemetry", "p3a"]),
    ("brave", "news-off", "BraveNewsDisabled", 1, "optional",
     "Brave: turn off Brave News",
     "The Brave News feed on the new tab page is unavailable.",
     "The new tab page has no news or promotional content.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["news"]),
    ("brave", "talk-off", "BraveTalkDisabled", 1, "optional",
     "Brave: turn off Brave Talk",
     "The Brave Talk video calling service is unavailable.",
     "Video calls go only through services approved by the organization.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["talk", "video calls"]),
    ("brave", "playlist-off", "BravePlaylistEnabled", 0, "optional",
     "Brave: turn off Playlist",
     "The feature for saving video and audio for offline viewing (Playlist) is unavailable.",
     "Media files do not accumulate in the browser profile.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["playlist", "media"]),
    ("brave", "speedreader-off", "BraveSpeedreaderEnabled", 0, "optional",
     "Brave: turn off Speedreader",
     "The Speedreader simplified reading mode is unavailable.",
     "Fewer built-in features that change how pages look.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["speedreader", "reading"]),
    ("brave", "wayback-off", "BraveWaybackMachineEnabled", 0, "optional",
     "Brave: no Wayback Machine prompts",
     "Brave does not offer to open an archived copy of an unavailable page in the Wayback Machine.",
     "Addresses of unavailable pages are not sent to the internet archive.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["wayback", "archive"]),
    ("brave", "web-discovery-off", "BraveWebDiscoveryEnabled", 0, "optional",
     "Brave: turn off Web Discovery",
     "Brave does not share information about visited pages to populate its search index.",
     "Addresses of visited sites are not sent to Brave Search.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["web discovery", "search", "telemetry"]),
    ("brave", "translate-off", "TranslateEnabled", 0, "optional",
     "Brave: do not offer page translation",
     "Brave does not offer to translate a page written in another language.",
     "Page text is not sent to a cloud translation service.",
     "Employees who read foreign-language websites lose built-in translation.", "Brave policies; they take effect if Brave is installed.",
     ["translation", "translate"]),
    ("brave", "tor-off", "TorDisabled", 1, "recommended",
     "Brave: block Tor windows",
     "Private windows connected to the Tor network are unavailable in Brave.",
     "Browser traffic does not go to the Tor network, bypassing the organization's filtering and logs.",
     "", "Brave policies; they take effect if Brave is installed.",
     ["tor", "network", "anonymity"]),
]


# Rules on by default, so in every preset built from the defaults: the selection of commit d33fc41 (26.09.2026)
# and the Edge AI policies of the customer list MoreOptions (28.09.2026). The rest stay off.
DEFAULT_ON = {
    "edge.diagnostic-data-off", "edge.search-telemetry-off", "edge.shopping-off", "edge.rewards-off",
    "edge.insider-promo-off", "edge.translate-off", "edge.feedback-off", "edge.autofill-cards-off",
    # 28.09.2026, customer list MoreOptions: AI in Edge off; sign-in off so that the AI policies apply
    "edge.sidebar-off", "edge.signin-off", "edge.genai-local-model-off", "edge.builtin-ai-apis-off",
    "edge.history-ai-search-off", "edge.ai-themes-off", "edge.text-prediction-off", "edge.tab-services-off",
    "edge.autofill-ml-off", "edge.copilot-address-bar-off", "edge.ntp-copilot-off", "edge.copilot-cowork-off",
    "edge.browsing-with-copilot-off", "edge.copilot-page-context-off", "edge.entra-copilot-page-context-off",
    "edge.m365-copilot-icon-off", "edge.compose-inline-off", "edge.copilot-search-history-off",
    "chrome.metrics-off", "chrome.variations", "chrome.background-off", "chrome.genai-off",
    "chrome.genai-local-model-off", "chrome.devtools-genai-off", "chrome.translate-off", "chrome.cast-private-only",
    "chrome.promotions-off", "chrome.autofill-cards-off",
    "brave.rewards-off", "brave.wallet-off", "brave.vpn-off", "brave.ai-chat-off", "brave.stats-ping-off",
    "brave.p3a-off", "brave.news-off", "brave.talk-off", "brave.playlist-off", "brave.speedreader-off",
    "brave.wayback-off", "brave.web-discovery-off", "brave.translate-off", "brave.tor-off",
}


def catalog_file() -> dict:
    known = {f"{r[0]}.{r[1]}" for r in RULES}
    assert DEFAULT_ON <= known, sorted(DEFAULT_ON - known)
    rules = []
    for browser, suffix, name, value, level, title, summary, effect, risk, versions, tags in RULES:
        path, group, anchor, product = PATHS[browser]
        rule = {
            "id": f"{browser}.{suffix}",
            "group": group,
            "phase": "specialize",
            "title": title,
            "level": level,
            "default": f"{browser}.{suffix}" in DEFAULT_ON,
            "tags": list(dict.fromkeys([product.lower(), "browser", "policy", name.lower()] + tags)),
            "doc": f"{DOC}#{anchor}",
            "summary": summary,
            "effect": effect,
        }
        if risk:
            rule["risk"] = risk
        rule["versions"] = versions
        param = value if isinstance(value, tuple) else None
        if param:
            pname, ptitle, default, options = param
            rule["params"] = {pname: {"type": "enum", "title": ptitle, "default": default,
                                      "values": [{"value": v, "title": t} for v, t in options]}}
        rule["actions"] = [{"type": "reg", "path": path, "name": name, "kind": "DWord",
                            "value": f"{{{param[0]}}}" if param else value}]
        rules.append(rule)
    return {
        "comment": ["Browsers: Microsoft Edge, Google Chrome, Brave (issue #1). Generated by tools/make_browser_rules.py;",
                    "edit the table in that tool, not this file. The rules on by default are listed in DEFAULT_ON."],
        "rules": rules,
    }


if __name__ == "__main__":
    target = ROOT / "rules" / "14-browsers.json"
    jsonfile.write(target, catalog_file())
    print(f"written {target.relative_to(ROOT)}: {len(RULES)} rules")
