<#
.SYNOPSIS
    Applies selected WinKickOff rules to this running Windows. Read it before running.
.DESCRIPTION
    Generated by WinKickOff. Run as administrator, first on a test computer or a virtual machine.
    Before every registry value, service start type or optional feature is changed, its previous state is
    saved to backup-<time>.json next to this script; Undo-Apply.ps1 restores it. Removed apps and
    capabilities and scripted steps cannot be restored automatically: see the rollback text of the rule
    in WinKickOff. Log: apply-<time>.log next to this script. A restart is recommended afterwards.
#>

$ErrorActionPreference = 'Continue'
{{build_label}}
$Here = Split-Path -Parent $MyInvocation.MyCommand.Path
$Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$LogPath = Join-Path $Here "apply-$Stamp.log"
$BackupPath = Join-Path $Here "backup-$Stamp.json"

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -Path $LogPath -Value $line -Encoding UTF8
}

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Log 'administrator rights are required; nothing was changed' 'ERROR'
    exit 1
}
Write-Log "apply started on $env:COMPUTERNAME by $env:USERNAME"

$script:Backup = New-Object System.Collections.Generic.List[object]

function Save-RegState {
    # Remembers the value as it was before the first change in this run.
    param([string]$Path, [string]$Name)
    if ($script:Backup | Where-Object { $_.kind -eq 'reg' -and $_.path -eq $Path -and $_.name -eq $Name }) { return }
    $entry = [ordered]@{ kind = 'reg'; path = $Path; name = $Name; existed = $false; type = $null; value = $null }
    try {
        $key = Get-Item -LiteralPath $Path -ErrorAction Stop
        $n = if ($Name -eq '(Default)') { '' } else { $Name }
        if (@($key.GetValueNames()) -contains $n) {
            $v = $key.GetValue($n, $null, 'DoNotExpandEnvironmentNames')
            $entry.existed = $true
            $entry.type = $key.GetValueKind($n).ToString()
            $entry.value = if ($v -is [byte[]]) { @($v | ForEach-Object { [int]$_ }) } else { $v }
        }
    } catch { }
    $script:Backup.Add([pscustomobject]$entry)
}

function Set-Reg {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][ValidateSet('DWord','QWord','String','ExpandString','MultiString','Binary')][string]$Type,
        [Parameter(Mandatory)][AllowEmptyString()][AllowNull()]$Value,
        [string]$Why = ''
    )
    Save-RegState $Path $Name
    try {
        if (-not (Test-Path -LiteralPath $Path)) { $null = New-Item -Path $Path -Force }
        Set-ItemProperty -LiteralPath $Path -Name $Name -Value $Value -Type $Type -Force
        Write-Log ("{0}\{1} = {2}  {3}" -f $Path, $Name, ($Value -join ','), $Why) 'OK'
    } catch {
        Write-Log ("FAILED {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

function Remove-Reg {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Name)
    Save-RegState $Path $Name
    try {
        if ((Test-Path -LiteralPath $Path) -and ($null -ne (Get-ItemProperty -LiteralPath $Path -Name $Name -ErrorAction SilentlyContinue))) {
            Remove-ItemProperty -LiteralPath $Path -Name $Name -Force
            Write-Log ("removed {0}\{1}" -f $Path, $Name) 'OK'
        }
    } catch {
        Write-Log ("FAILED to remove {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

function Set-ServiceStart {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][int]$Start)
    $key = "HKLM:\SYSTEM\CurrentControlSet\Services\$Name"
    if (Test-Path $key) { Set-Reg -Path $key -Name 'Start' -Type DWord -Value $Start -Why "service $Name" }
    else { Write-Log "service $Name not present, skipped" }
}

function Invoke-Exe {
    param([Parameter(Mandatory)][string]$File, [string[]]$Arguments = @())
    try {
        $out = & $File @Arguments 2>&1
        $code = $LASTEXITCODE
        Write-Log ("{0} {1} -> exit {2}" -f $File, ($Arguments -join ' '), $code) $(if ($code -eq 0) { 'OK' } else { 'WARN' })
        if ($code -ne 0 -and $out) { Write-Log (($out | Out-String).Trim()) 'WARN' }
    } catch {
        Write-Log ("FAILED {0} {1}: {2}" -f $File, ($Arguments -join ' '), $_.Exception.Message) 'ERROR'
    }
}

function Set-Feature {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][ValidateSet('Enabled','Disabled')][string]$State)
    try {
        $f = Get-WindowsOptionalFeature -Online -FeatureName $Name -ErrorAction SilentlyContinue
        if (-not $f) { Write-Log "feature $Name not present on this build, skipped"; return }
        $script:Backup.Add([pscustomobject]@{ kind = 'feature'; name = $Name; state = [string]$f.State })
        if ($State -eq 'Disabled' -and $f.State -notlike 'Disabled*') {
            $null = Disable-WindowsOptionalFeature -Online -FeatureName $Name -NoRestart -ErrorAction Stop
            Write-Log "feature $Name disabled" 'OK'
        } elseif ($State -eq 'Enabled' -and $f.State -ne 'Enabled') {
            $null = Enable-WindowsOptionalFeature -Online -FeatureName $Name -All -NoRestart -ErrorAction Stop
            Write-Log "feature $Name enabled" 'OK'
        } else {
            Write-Log "feature $Name already $($f.State)"
        }
    } catch { Write-Log ("feature {0}: {1}" -f $Name, $_.Exception.Message) 'WARN' }
}

function Remove-Capability {
    param([Parameter(Mandatory)][string]$Pattern)
    try {
        $caps = @(Get-WindowsCapability -Online -Name $Pattern -ErrorAction Stop | Where-Object State -eq 'Installed')
        if (-not $caps) { Write-Log "capability $Pattern not installed, skipped"; return }
        foreach ($c in $caps) {
            try {
                $null = Remove-WindowsCapability -Online -Name $c.Name -ErrorAction Stop
                $script:Backup.Add([pscustomobject]@{ kind = 'capability-removed'; name = $c.Name })
                Write-Log "removed capability $($c.Name)" 'OK'
            } catch { Write-Log ("capability {0}: {1}" -f $c.Name, $_.Exception.Message) 'WARN' }
        }
    } catch { Write-Log ("capability {0}: {1}" -f $Pattern, $_.Exception.Message) 'WARN' }
}

function Remove-Apps {
    param([Parameter(Mandatory)][string[]]$Names)
    foreach ($app in $Names) {
        $found = $false
        foreach ($p in @(Get-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Where-Object DisplayName -eq $app)) {
            $found = $true
            try { $null = Remove-AppxProvisionedPackage -Online -PackageName $p.PackageName -ErrorAction Stop; Write-Log "deprovisioned $($p.PackageName)" 'OK' }
            catch { Write-Log ("deprovision {0}: {1}" -f $p.PackageName, $_.Exception.Message) 'WARN' }
        }
        foreach ($p in @(Get-AppxPackage -AllUsers -Name $app -ErrorAction SilentlyContinue)) {
            $found = $true
            try { Remove-AppxPackage -Package $p.PackageFullName -AllUsers -ErrorAction Stop; Write-Log "removed $($p.PackageFullName)" 'OK' }
            catch { Write-Log ("remove {0}: {1}" -f $p.PackageFullName, $_.Exception.Message) 'WARN' }
        }
        if ($found) { $script:Backup.Add([pscustomobject]@{ kind = 'app-removed'; name = $app }) }
        else { Write-Log "app $app not present, skipped" }
    }
}

if (-not (Get-PSDrive -Name HKU -ErrorAction SilentlyContinue)) {
    $null = New-PSDrive -Name HKU -PSProvider Registry -Root HKEY_USERS -ErrorAction SilentlyContinue
}
$du = 'HKU:\UnattendDefault'
function Mount-DefaultUser {
    # The default user profile, inherited by accounts created from now on.
    $r = & reg.exe load 'HKU\UnattendDefault' 'C:\Users\Default\NTUSER.DAT' 2>&1
    if ($LASTEXITCODE -eq 0) { Write-Log 'default user hive loaded' 'OK'; return $true }
    Write-Log "reg load failed: $r" 'ERROR'
    return $false
}
function Dismount-DefaultUser {
    [gc]::Collect(); [gc]::WaitForPendingFinalizers(); Start-Sleep -Seconds 1
    $r = & reg.exe unload 'HKU\UnattendDefault' 2>&1
    if ($LASTEXITCODE -eq 0) { Write-Log 'default user hive unloaded' 'OK' } else { Write-Log "reg unload: $r" 'WARN' }
}

trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

$accounts = @({{accounts}})

{{blocks}}

$script:Backup | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $BackupPath -Encoding UTF8
Write-Log "backup saved to $BackupPath" 'OK'
Write-Log 'apply finished; restart the computer so that system policies and services take effect'
exit 0
