<#
.SYNOPSIS
    Read-only audit: do the selected WinKickOff rules take effect on this computer?
.DESCRIPTION
    Generated by WinKickOff. The script only reads (registry, service start types, optional features,
    capabilities, apps) and writes one JSON report to the path given in -Report. It changes nothing.
    Without administrator rights components, capabilities and apps of other users cannot be read; such
    checks are reported as unknown. Values of the default user profile are checked in HKCU of the current
    user, the closest equivalent on a running system.
#>
param([Parameter(Mandatory)][string]$Report)

$ErrorActionPreference = 'Continue'
{{build_label}}
$IsAdmin = (New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
$Results = New-Object System.Collections.Generic.List[object]

function Add-Result {
    param([string]$Rule, [string]$Check, [string]$Status, $Current, $Expected, [string]$Note = '')
    $Results.Add([pscustomobject]@{ rule = $Rule; check = $Check; status = $Status; current = (@($Current) -join ','); expected = (@($Expected) -join ','); note = $Note })
}

function Get-RegValue {
    # @{ found; value } without throwing; '(Default)' reads the default value of the key.
    param([string]$Path, [string]$Name)
    try {
        $key = Get-Item -LiteralPath $Path -ErrorAction Stop
        $n = if ($Name -eq '(Default)') { '' } else { $Name }
        if (@($key.GetValueNames()) -contains $n) { return @{ found = $true; value = $key.GetValue($n, $null, 'DoNotExpandEnvironmentNames') } }
    } catch { }
    return @{ found = $false; value = $null }
}

function Test-Reg {
    param([string]$Rule, [string]$Path, [string]$Name, [string]$Kind, $Expected, [string]$Note = '')
    $r = Get-RegValue $Path $Name
    if (-not $r.found) { Add-Result $Rule "$Path\$Name" 'differs' $null $Expected $Note; return }
    $current = $r.value
    $ok = if ($Kind -in 'DWord', 'QWord') { [int64]$current -eq [int64]$Expected }
          elseif ($Kind -in 'MultiString', 'Binary') { (@($current) -join ',') -eq (@($Expected) -join ',') }
          else { [string]$current -eq [string]$Expected }
    Add-Result $Rule "$Path\$Name" $(if ($ok) { 'ok' } else { 'differs' }) $current $Expected $Note
}

function Test-RegAbsent {
    param([string]$Rule, [string]$Path, [string]$Name, [string]$Note = '')
    $r = Get-RegValue $Path $Name
    Add-Result $Rule "$Path\$Name" $(if ($r.found) { 'differs' } else { 'ok' }) $r.value '(absent)' $Note
}

function Test-ServiceStart {
    param([string]$Rule, [string]$Name, [int]$Start)
    $r = Get-RegValue "HKLM:\SYSTEM\CurrentControlSet\Services\$Name" 'Start'
    if (-not $r.found) { Add-Result $Rule "service $Name" 'unknown' $null $Start 'service not present'; return }
    Add-Result $Rule "service $Name" $(if ([int]$r.value -eq $Start) { 'ok' } else { 'differs' }) $r.value $Start
}

function Test-Feature {
    param([string]$Rule, [string]$Name, [string]$State)
    if (-not $IsAdmin) { Add-Result $Rule "feature $Name" 'unknown' $null $State 'administrator rights needed'; return }
    try {
        $f = Get-WindowsOptionalFeature -Online -FeatureName $Name -ErrorAction Stop
        if (-not $f) { Add-Result $Rule "feature $Name" 'ok' 'absent' $State 'not present on this build'; return }
        Add-Result $Rule "feature $Name" $(if ([string]$f.State -like "$State*") { 'ok' } else { 'differs' }) $f.State $State
    } catch { Add-Result $Rule "feature $Name" 'unknown' $null $State $_.Exception.Message }
}

function Test-CapabilityAbsent {
    param([string]$Rule, [string]$Pattern)
    if (-not $IsAdmin) { Add-Result $Rule "capability $Pattern" 'unknown' $null 'NotPresent' 'administrator rights needed'; return }
    try {
        $caps = @(Get-WindowsCapability -Online -Name $Pattern -ErrorAction Stop | Where-Object State -eq 'Installed')
        Add-Result $Rule "capability $Pattern" $(if ($caps.Count -eq 0) { 'ok' } else { 'differs' }) (@($caps | ForEach-Object Name) -join ',') 'NotPresent'
    } catch { Add-Result $Rule "capability $Pattern" 'unknown' $null 'NotPresent' $_.Exception.Message }
}

function Test-AppAbsent {
    param([string]$Rule, [string]$Name)
    try {
        $pkgs = if ($IsAdmin) { @(Get-AppxPackage -AllUsers -Name $Name -ErrorAction Stop) } else { @(Get-AppxPackage -Name $Name -ErrorAction Stop) }
        $note = if ($IsAdmin) { '' } else { 'current user only' }
        Add-Result $Rule "app $Name" $(if ($pkgs.Count -eq 0) { 'ok' } else { 'differs' }) (@($pkgs | ForEach-Object PackageFullName) -join ',') '(absent)' $note
    } catch { Add-Result $Rule "app $Name" 'unknown' $null '(absent)' $_.Exception.Message }
}

function Add-Unknown {
    param([string]$Rule, [string]$What)
    Add-Result $Rule $What 'unknown' $null $null 'cannot be checked automatically'
}

{{blocks}}

$out = [pscustomobject]@{ computer = $env:COMPUTERNAME; admin = $IsAdmin; time = (Get-Date -Format s); results = $Results }
$out | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $Report -Encoding UTF8
exit 0
