<#
.SYNOPSIS
    Runs as SYSTEM at every startup until OOBE has completed, then applies the post-OOBE rules of
    the WinKickOff profile and removes its own scheduled task. Generated by WinKickOff.
    Every block starts with a "# [rule.id]" marker; disabled rules are absent.
#>
$ErrorActionPreference = 'Continue'
$log = 'C:\ProgramData\Unattend\Logs\Post-OOBE.log'
function Write-Log { param([string]$m, [string]$Level = 'INFO') try { Add-Content -Path $log -Value ('[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $m) -Encoding UTF8 } catch {} }
trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

# Local accounts created by the answer file (used by rules that act on every starter account).
$accounts = @({{accounts}})

Write-Log 'Post-OOBE.ps1 started'
$stateKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\State'
$state = $null
$deadline = (Get-Date).AddHours(5)
while ((Get-Date) -lt $deadline) {
    $state = (Get-ItemProperty -Path $stateKey -Name ImageState -ErrorAction SilentlyContinue).ImageState
    if ($state -eq 'IMAGE_STATE_COMPLETE') { break }
    Start-Sleep -Seconds 30
}
if ($state -ne 'IMAGE_STATE_COMPLETE') { Write-Log "OOBE still not complete ($state), will retry at next startup"; exit 0 }
Write-Log 'OOBE complete, waiting 2 minutes for the first sign-in to settle'
Start-Sleep -Seconds 120

{{blocks}}

try { $null = & schtasks.exe /Delete /TN 'Unattend-PostOOBE' /F 2>&1; Write-Log "task removed (exit $LASTEXITCODE)" } catch { Write-Log "task removal: $($_.Exception.Message)" }
Write-Log 'Post-OOBE.ps1 finished'
exit 0
