<#
.SYNOPSIS
    Runs as SYSTEM at every startup until OOBE has completed, then applies the post-OOBE rules of
    the WinKickOff profile and removes its own scheduled task. Generated by WinKickOff.
    Every block starts with a "# [rule.id]" marker; disabled rules are absent.
#>
$ErrorActionPreference = 'Continue'
$log = 'C:\ProgramData\Unattend\Logs\Post-OOBE.log'
function Write-Log { param([string]$m, [string]$Level = 'INFO') try { Add-Content -Path $log -Value ('[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $m) -Encoding UTF8 } catch {} }
trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

# Registry writes of the rules of this script (the same as in Setup-System.ps1, logging into this script's log).
function Set-Reg {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][ValidateSet('DWord','QWord','String','ExpandString','MultiString','Binary')][string]$Type,
        [Parameter(Mandatory)][AllowEmptyString()][AllowEmptyCollection()][AllowNull()]$Value,
        [string]$Why = ''
    )
    try {
        if (-not (Test-Path -LiteralPath $Path)) { $null = New-Item -Path $Path -Force }
        Set-ItemProperty -LiteralPath $Path -Name $Name -Value $Value -Type $Type -Force
        Write-Log ("{0}\{1} = {2}  {3}" -f $Path, $Name, ($Value -join ','), $Why) 'OK'
    } catch {
        Write-Log ("FAILED {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}
function Remove-Reg {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Name)
    try {
        if ((Test-Path -LiteralPath $Path) -and ($null -ne (Get-ItemProperty -LiteralPath $Path -Name $Name -ErrorAction SilentlyContinue))) {
            Remove-ItemProperty -LiteralPath $Path -Name $Name -Force
            Write-Log ("removed {0}\{1}" -f $Path, $Name) 'OK'
        }
    } catch {
        Write-Log ("FAILED to remove {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

# Local accounts created by the answer file (used by rules that act on every starter account).
$accounts = @({{accounts}})

# Display names and descriptions outside ASCII: Windows Setup 24H2 and later turns such characters of the answer file
# into question marks, so the answer file holds the account name and no description, and this script sets the texts
# (UTF-8 in Base64, which keeps the answer file ASCII). ADSI, since Set-LocalUser takes at most 48 characters.
function ConvertFrom-Base64Text { param([string]$Text) [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Text)) }
function Set-AccountText {
    param([Parameter(Mandatory)][string]$Name, [string]$FullName, [string]$Description)
    try {
        $user = [ADSI]('WinNT://{0}/{1},user' -f $env:COMPUTERNAME, $Name)
        if ($FullName) { $user.Put('FullName', $FullName) }
        if ($Description) { $user.Put('Description', $Description) }
        $user.SetInfo()
        Write-Log ("account {0}: display name and description set" -f $Name) 'OK'
    } catch {
        Write-Log ("FAILED account {0}: {1}" -f $Name, $_.Exception.Message) 'ERROR'
    }
}

Write-Log 'Post-OOBE.ps1 started'
$stateKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\State'
$state = $null
$deadline = (Get-Date).AddHours(5)
while ((Get-Date) -lt $deadline) {
    $state = (Get-ItemProperty -Path $stateKey -Name ImageState -ErrorAction SilentlyContinue).ImageState
    if ($state -eq 'IMAGE_STATE_COMPLETE') { break }
    Start-Sleep -Seconds 30
}
if ($state -ne 'IMAGE_STATE_COMPLETE') { Write-Log "OOBE still not complete ($state), will retry at next startup"; exit 0 }
{{account_texts}}
Write-Log 'OOBE complete, waiting 2 minutes for the first sign-in to settle'
Start-Sleep -Seconds 120

{{blocks}}

try { $null = & schtasks.exe /Delete /TN 'Unattend-PostOOBE' /F 2>&1; Write-Log "task removed (exit $LASTEXITCODE)" } catch { Write-Log "task removal: $($_.Exception.Message)" }
Write-Log 'Post-OOBE.ps1 finished'
exit 0
