<#
.SYNOPSIS
    Per-user settings, generated by WinKickOff. Started by Active Setup once at the first
    sign-in of every user (runs as that user, without elevation).
    Every block starts with a "# [rule.id]" marker; disabled rules are absent.
#>
$ErrorActionPreference = 'Continue'
# One log per user: a file created by the first user is not writable by the next one under ProgramData.
$log = "C:\ProgramData\Unattend\Logs\Setup-User.$($env:USERNAME).log"
function Write-Log { param([string]$m, [string]$Level = 'INFO') try { Add-Content -Path $log -Value ('[{0}] [{1}] [{2}] {3}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $env:USERNAME, $Level, $m) -Encoding UTF8 } catch {} }
trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

# Input languages of the profile, in order. Transient languages (no numeric locale id, such as ru-UA)
# must get a keyboard layout from Windows; otherwise the fallback list is applied.
$InputLanguages = @({{input_languages}})
$InputFallback = @({{input_fallback}})
$TransientLanguages = @({{transient_languages}})

Write-Log 'Setup-User.ps1 started'

{{blocks}}

Write-Log 'Setup-User.ps1 finished'
exit 0
