<#
.SYNOPSIS
    Machine-wide configuration of a workgroup Windows PC, generated by WinKickOff.
    Runs once, as SYSTEM, during the "specialize" pass of Windows Setup.
.NOTES
    Assembled from the enabled rules of the WinKickOff catalog: every block starts with a
    "# [rule.id]" marker and disabled rules are absent. The helper functions below are the
    fixed runtime and do not depend on the profile.
    Log: C:\ProgramData\Unattend\Logs\Setup-System.log
#>

$ErrorActionPreference = 'Continue'

# ============================================================================
# RUNTIME
# ============================================================================
$LogDir  = 'C:\ProgramData\Unattend\Logs'
$LogPath = Join-Path $LogDir 'Setup-System.log'
$null = New-Item -Path $LogDir -ItemType Directory -Force -ErrorAction SilentlyContinue

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -Path $LogPath -Value $line -Encoding UTF8
}

function Set-Reg {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][ValidateSet('DWord','QWord','String','ExpandString','MultiString','Binary')][string]$Type,
        [Parameter(Mandatory)][AllowEmptyString()][AllowNull()]$Value,
        [string]$Why = ''
    )
    try {
        if (-not (Test-Path -LiteralPath $Path)) { $null = New-Item -Path $Path -Force }
        Set-ItemProperty -LiteralPath $Path -Name $Name -Value $Value -Type $Type -Force
        Write-Log ("{0}\{1} = {2}  {3}" -f $Path, $Name, ($Value -join ','), $Why) 'OK'
    } catch {
        Write-Log ("FAILED {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

function Remove-Reg {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Name)
    try {
        if ((Test-Path -LiteralPath $Path) -and ($null -ne (Get-ItemProperty -LiteralPath $Path -Name $Name -ErrorAction SilentlyContinue))) {
            Remove-ItemProperty -LiteralPath $Path -Name $Name -Force
            Write-Log ("removed {0}\{1}" -f $Path, $Name) 'OK'
        }
    } catch {
        Write-Log ("FAILED to remove {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

function Set-ServiceStart {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][int]$Start)  # 2 auto, 3 manual, 4 disabled
    $key = "HKLM:\SYSTEM\CurrentControlSet\Services\$Name"
    if (Test-Path $key) { Set-Reg -Path $key -Name 'Start' -Type DWord -Value $Start -Why "service $Name" }
    else { Write-Log "service $Name not present, skipped" }
}

function Invoke-Exe {
    # Runs a native executable directly (no cmd.exe quoting problems) and logs its exit code.
    param([Parameter(Mandatory)][string]$File, [string[]]$Arguments = @())
    try {
        $out = & $File @Arguments 2>&1
        $code = $LASTEXITCODE
        Write-Log ("{0} {1} -> exit {2}" -f $File, ($Arguments -join ' '), $code) $(if ($code -eq 0) { 'OK' } else { 'WARN' })
        if ($code -ne 0 -and $out) { Write-Log (($out | Out-String).Trim()) 'WARN' }
    } catch {
        Write-Log ("FAILED {0} {1}: {2}" -f $File, ($Arguments -join ' '), $_.Exception.Message) 'ERROR'
    }
}

function Set-Feature {
    # Optional Windows feature; a feature absent from this build is logged and skipped.
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][ValidateSet('Enabled','Disabled')][string]$State)
    try {
        $f = Get-WindowsOptionalFeature -Online -FeatureName $Name -ErrorAction SilentlyContinue
        if (-not $f) { Write-Log "feature $Name not present on this build, skipped"; return }
        if ($State -eq 'Disabled' -and $f.State -notlike 'Disabled*') {
            $null = Disable-WindowsOptionalFeature -Online -FeatureName $Name -NoRestart -ErrorAction Stop
            Write-Log "feature $Name disabled" 'OK'
        } elseif ($State -eq 'Enabled' -and $f.State -ne 'Enabled') {
            $null = Enable-WindowsOptionalFeature -Online -FeatureName $Name -All -NoRestart -ErrorAction Stop
            Write-Log "feature $Name enabled" 'OK'
        } else {
            Write-Log "feature $Name already $($f.State)"
        }
    } catch { Write-Log ("feature {0}: {1}" -f $Name, $_.Exception.Message) 'WARN' }
}

function Remove-Capability {
    param([Parameter(Mandatory)][string]$Pattern)
    try {
        $caps = @(Get-WindowsCapability -Online -Name $Pattern -ErrorAction Stop | Where-Object State -eq 'Installed')
        if (-not $caps) { Write-Log "capability $Pattern not installed, skipped"; return }
        foreach ($c in $caps) {
            try { $null = Remove-WindowsCapability -Online -Name $c.Name -ErrorAction Stop; Write-Log "removed capability $($c.Name)" 'OK' }
            catch { Write-Log ("capability {0}: {1}" -f $c.Name, $_.Exception.Message) 'WARN' }
        }
    } catch { Write-Log ("capability {0}: {1}" -f $Pattern, $_.Exception.Message) 'WARN' }
}

# Appx packages are listed once and reused by every Remove-Apps call (listing is slow).
$script:AppxCache = $null
function Remove-Apps {
    param([Parameter(Mandatory)][string[]]$Names)
    if ($null -eq $script:AppxCache) {
        $provisioned = @()
        $installed = @()
        try { $provisioned = @(Get-AppxProvisionedPackage -Online -ErrorAction Stop) } catch { Write-Log "Get-AppxProvisionedPackage: $($_.Exception.Message)" 'WARN' }
        try { $installed = @(Get-AppxPackage -AllUsers -ErrorAction Stop) } catch { Write-Log "Get-AppxPackage: $($_.Exception.Message)" 'WARN' }
        $script:AppxCache = @{ Provisioned = $provisioned; Installed = $installed }
    }
    foreach ($app in $Names) {
        $found = $false
        foreach ($p in @($script:AppxCache.Provisioned | Where-Object DisplayName -eq $app)) {
            $found = $true
            try { $null = Remove-AppxProvisionedPackage -Online -PackageName $p.PackageName -ErrorAction Stop; Write-Log "deprovisioned $($p.PackageName)" 'OK' }
            catch { Write-Log ("deprovision {0}: {1}" -f $p.PackageName, $_.Exception.Message) 'WARN' }
        }
        foreach ($p in @($script:AppxCache.Installed | Where-Object Name -eq $app)) {
            $found = $true
            try { Remove-AppxPackage -Package $p.PackageFullName -AllUsers -ErrorAction Stop; Write-Log "removed $($p.PackageFullName)" 'OK' }
            catch { Write-Log ("remove {0}: {1}" -f $p.PackageFullName, $_.Exception.Message) 'WARN' }
        }
        if (-not $found) { Write-Log "app $app not present, skipped" }
    }
}

# Any unexpected terminating error is logged and execution continues with the next statement.
# Windows Setup aborts the whole installation if this script ends with a non-zero exit code.
trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

if (-not (Get-PSDrive -Name HKU -ErrorAction SilentlyContinue)) {
    $null = New-PSDrive -Name HKU -PSProvider Registry -Root HKEY_USERS -ErrorAction SilentlyContinue
}

Write-Log '================================================================'
Write-Log 'Setup-System.ps1 started: {{build_label}}'
Write-Log ("Build: {0}  User: {1}" -f [System.Environment]::OSVersion.Version.Build, $env:USERNAME)

# ============================================================================
# RULES
# ============================================================================
{{blocks}}

{{default_user_section}}

{{active_setup_section}}

{{post_oobe_section}}

Write-Log 'Setup-System.ps1 finished'
exit 0
