<#
.SYNOPSIS
    Per-user settings, generated by WinKickOff. Started by Active Setup once at the first
    sign-in of every user (runs as that user, without elevation).
    Every block starts with a "# [rule.id]" marker; disabled rules are absent.
#>
$ErrorActionPreference = 'Continue'
# One log per user: a file created by the first user is not writable by the next one under ProgramData.
$log = "C:\ProgramData\Unattend\Logs\Setup-User.$($env:USERNAME).log"
function Write-Log { param([string]$m, [string]$Level = 'INFO') try { Add-Content -Path $log -Value ('[{0}] [{1}] [{2}] {3}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $env:USERNAME, $Level, $m) -Encoding UTF8 } catch {} }
trap { Write-Log ("UNHANDLED: {0} (line {1})" -f $_.Exception.Message, $_.InvocationInfo.ScriptLineNumber) 'ERROR'; continue }

# Registry writes of the rules of this script (the same as in Setup-System.ps1, logging into this script's log).
function Set-Reg {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][ValidateSet('DWord','QWord','String','ExpandString','MultiString','Binary')][string]$Type,
        [Parameter(Mandatory)][AllowEmptyString()][AllowEmptyCollection()][AllowNull()]$Value,
        [string]$Why = ''
    )
    try {
        if (-not (Test-Path -LiteralPath $Path)) { $null = New-Item -Path $Path -Force }
        Set-ItemProperty -LiteralPath $Path -Name $Name -Value $Value -Type $Type -Force
        Write-Log ("{0}\{1} = {2}  {3}" -f $Path, $Name, ($Value -join ','), $Why) 'OK'
    } catch {
        Write-Log ("FAILED {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}
function Remove-Reg {
    param([Parameter(Mandatory)][string]$Path, [Parameter(Mandatory)][string]$Name)
    try {
        if ((Test-Path -LiteralPath $Path) -and ($null -ne (Get-ItemProperty -LiteralPath $Path -Name $Name -ErrorAction SilentlyContinue))) {
            Remove-ItemProperty -LiteralPath $Path -Name $Name -Force
            Write-Log ("removed {0}\{1}" -f $Path, $Name) 'OK'
        }
    } catch {
        Write-Log ("FAILED to remove {0}\{1}: {2}" -f $Path, $Name, $_.Exception.Message) 'ERROR'
    }
}

# Input languages of the profile, in order. Transient languages (no numeric locale id, such as ru-UA)
# must get a keyboard layout from Windows; otherwise the fallback list is applied.
$InputLanguages = @({{input_languages}})
$InputFallback = @({{input_fallback}})
$TransientLanguages = @({{transient_languages}})

Write-Log 'Setup-User.ps1 started'

{{blocks}}

Write-Log 'Setup-User.ps1 finished'
exit 0
