<#
.SYNOPSIS
    Restores what Apply-*.ps1 changed, from its backup-<time>.json.
.DESCRIPTION
    Generated by WinKickOff. Run as administrator. Without -BackupPath the newest backup-*.json next to
    this script is used. Registry values and service start types get their previous values back (values
    that did not exist are deleted; a list of values is saved and restored value by value, so its deleted
    values come back and its new ones go); optional features return to their previous state. Removed apps and
    capabilities are only listed: reinstall them from Microsoft Store or with Add-WindowsCapability.
    Log: undo-<time>.log next to this script.
#>
param([string]$BackupPath = '')

$ErrorActionPreference = 'Continue'
{{build_label}}
$Here = Split-Path -Parent $MyInvocation.MyCommand.Path
$LogPath = Join-Path $Here ("undo-{0}.log" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $line = '[{0}] [{1}] {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message
    Add-Content -Path $LogPath -Value $line -Encoding UTF8
}

$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Log 'administrator rights are required; nothing was changed' 'ERROR'
    exit 1
}
if (-not $BackupPath) {
    $BackupPath = Get-ChildItem -LiteralPath $Here -Filter 'backup-*.json' | Sort-Object Name | Select-Object -Last 1 -ExpandProperty FullName
}
if (-not $BackupPath -or -not (Test-Path -LiteralPath $BackupPath)) { Write-Log 'no backup file found; nothing to restore' 'ERROR'; exit 1 }
Write-Log "restoring from $BackupPath"
$entries = @(Get-Content -LiteralPath $BackupPath -Raw -Encoding UTF8 | ConvertFrom-Json)

if (-not (Get-PSDrive -Name HKU -ErrorAction SilentlyContinue)) {
    $null = New-PSDrive -Name HKU -PSProvider Registry -Root HKEY_USERS -ErrorAction SilentlyContinue
}
$mounted = $false
if ($entries | Where-Object { $_.kind -eq 'reg' -and $_.path -like 'HKU:\UnattendDefault*' }) {
    $r = & reg.exe load 'HKU\UnattendDefault' 'C:\Users\Default\NTUSER.DAT' 2>&1
    if ($LASTEXITCODE -eq 0) { $mounted = $true } else { Write-Log "reg load failed: $r" 'ERROR' }
}

[array]::Reverse($entries)
foreach ($e in $entries) {
    try {
        switch ($e.kind) {
            'reg' {
                if ($e.existed) {
                    if (-not (Test-Path -LiteralPath $e.path)) { $null = New-Item -Path $e.path -Force }
                    $value = switch ($e.type) {
                        'MultiString' { [string[]]@($e.value) }
                        'Binary' { [byte[]]@($e.value) }
                        'DWord' { [int]$e.value }
                        'QWord' { [long]$e.value }
                        default { [string]$e.value }
                    }
                    Set-ItemProperty -LiteralPath $e.path -Name $e.name -Value $value -Type $e.type -Force
                    Write-Log ("restored {0}\{1}" -f $e.path, $e.name) 'OK'
                } elseif ($null -ne (Get-ItemProperty -LiteralPath $e.path -Name $e.name -ErrorAction SilentlyContinue)) {
                    Remove-ItemProperty -LiteralPath $e.path -Name $e.name -Force
                    Write-Log ("removed {0}\{1} (did not exist before)" -f $e.path, $e.name) 'OK'
                }
            }
            'feature' {
                if ([string]$e.state -like 'Enabled*') { $null = Enable-WindowsOptionalFeature -Online -FeatureName $e.name -All -NoRestart -ErrorAction Stop }
                else { $null = Disable-WindowsOptionalFeature -Online -FeatureName $e.name -NoRestart -ErrorAction Stop }
                Write-Log ("feature {0} back to {1}" -f $e.name, $e.state) 'OK'
            }
            default { Write-Log ("cannot be restored automatically: {0} {1}" -f $e.kind, $e.name) 'WARN' }
        }
    } catch { Write-Log ("FAILED to restore {0} {1}: {2}" -f $e.kind, $e.name, $_.Exception.Message) 'ERROR' }
}

if ($mounted) {
    [gc]::Collect(); [gc]::WaitForPendingFinalizers(); Start-Sleep -Seconds 1
    $null = & reg.exe unload 'HKU\UnattendDefault' 2>&1
}
Write-Log 'undo finished; restart the computer'
exit 0
